import {
  SwordIcon,
  HeartIcon,
  DropIcon,
  CoinsIcon,
  LightningIcon,
  ChartBarIcon,
  MagicWandIcon,
  ShieldIcon,
  UserIcon,
  TrashIcon,
  PlusIcon,
  MinusIcon,
  PencilSimpleIcon,
  ImageSquareIcon,
  StarIcon,
  SneakerMoveIcon,
  EyeIcon,
  CrownIcon,
  FloppyDiskBackIcon,
  BiohazardIcon,
  CatIcon,
  BookOpenTextIcon,
  PersonSimpleIcon,
} from "phosphor-react-native";

export const Icons = {
  sword: SwordIcon,
  heart: HeartIcon,
  mana: DropIcon,
  coin: CoinsIcon,
  lightning: LightningIcon,
  chart: ChartBarIcon,
  magic: MagicWandIcon,
  shield: ShieldIcon,
  user: UserIcon,
  trash: TrashIcon,
  plus: PlusIcon,
  minus: MinusIcon,
  edit: PencilSimpleIcon,
  image: ImageSquareIcon,
  star: StarIcon,
  agility: SneakerMoveIcon,
  stealth: EyeIcon,
  crown: CrownIcon,
  save: FloppyDiskBackIcon,
  MHUD: BiohazardIcon,
  cat: CatIcon,
  skills: BookOpenTextIcon,
  mc: PersonSimpleIcon,
};
